stop drum immediately if it is still starting
LLK/scratch-vm pull request #1266
Opened 2018-06-22 17:15 UTC by mzgoddard

### Resolves

`[forever [playDrumForBeats "Snare Drum" 0]]` makes a loud noise.

### Proposed Changes

Stop a starting drum sound immediately.

I've included the same logic into `playNote` though note's behaviour means this will never be called. I've included the second change to have reading parity with playDrum.

### Reason for Changes

Without stopping immediately, `[forever [playDrumForBeats "Snare Drum" 0]]` makes a bad loud noise. With stopping immediately the drum will play normally.

2018-06-22 17:22 UTC, gnarf requested changes
I think you should just do `&& !player.isStarting()` on the next if's instead, this forces clips and still sounds meh...

2018-06-22 17:23 UTC, gnarf commented
```diff
diff --git a/src/extensions/scratch3_music/index.js b/src/extensions/scratch3_music/index.js
index 6501d95..1ef4d69 100644
--- a/src/extensions/scratch3_music/index.js
+++ b/src/extensions/scratch3_music/index.js
@@ -786,11 +786,7 @@ class Scratch3MusicBlocks {
 
         if (typeof player === 'undefined') return;
 
-        if (player.isStarting) {
-            player.stopImmediately();
-        }
-
-        if (player.isPlaying) {
+        if (player.isPlaying && !player.isStarting) {
             // Take the internal player state and create a new player with it.
             // `.play` does this internally but then instructs the sound to
             // stop.
Stage this hunk [y,n,q,a,d,/,j,J,g,e,?]? y
@@ -893,11 +889,7 @@ class Scratch3MusicBlocks {
 
         const player = this._instrumentPlayerNoteArrays[inst][note];
 
-        if (player.isStarting) {
-            player.stopImmediately();
-        }
-
-        if (player.isPlaying) {
+        if (player.isPlaying && !player.isStarting) {
             // Take the internal player state and create a new player with it.
             // `.play` does this internally but then instructs the sound to
             // stop.
Stage this hunk [y,n,q,a,d,/,K,g,e,?]? y
```

2018-06-22 17:23 UTC, gnarf commented
sounds a lot better to me

2018-06-22 17:27 UTC, gnarf commented
It's pretty clear the old version just started it's max number of drums at once and then didn't start new ones, it's super loud

2018-06-22 17:47 UTC, gnarf approved these changes

2018-06-25 19:30 UTC, ericrosenbaum approved these changes
🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁

2018-06-25 19:31 UTC, merged