Fix benchmark suite
LLK/scratch-vm pull request #1397
Opened 2018-07-27 18:35 UTC by mzgoddard

### Proposed Changes

Add SVG and Bitmap adapters to scratch vm in benchmark suite.

### Reason for Changes

Benchmark is broken without the adapters.

2018-07-31 21:32 UTC, kchadha commented on src/playground/suite.js
> +    // }));
cruft?

2018-07-31 21:35 UTC, kchadha commented on src/playground/suite.js
> +    // Error: Cannot create monitor for target that cannot be found by name
Do you mind referencing issue #1322 in a TODO comment here?

2018-08-03 21:23 UTC, cwillisf requested changes
Looks like you need to tell the linter about `ScratchSVGRenderer`... other than that, LGTM

2018-08-07 20:43 UTC, cwillisf approved these changes

2018-08-08 18:36 UTC, merged