Allow localizing micro:bit blocks
LLK/scratch-vm pull request #1431
Opened 2018-08-07 16:08 UTC by technoboy10

### Resolves
This PR resolves #1421.

### Proposed Changes
This PR adds calls to `formatMessage` in the `getInfo` function to allow blocks to be translated, as well as moving micro:bit menus to separate getters and enums to allow them to be translated.

2018-08-08 15:10 UTC, chrisgarrity requested changes
Overall it looks great. Just a couple of things that I think will help translators.

2018-08-08 15:10 UTC, chrisgarrity commented on src/extensions/scratch3_microbit/index.js
> +                text: formatMessage({
Just confirmed with Kreg, the buttons are physically labelled 'A' and 'B', so these shouldn't get translated.

2018-08-08 15:10 UTC, chrisgarrity commented on src/extensions/scratch3_microbit/index.js
> +                            })
The micro:bit has a limited set of characters - we need to warn translators to only use numbers and 'a-zA-z'. How about:
`description: 'default text to display. IMPORTANT - the micro:bit only supports letters a-z, A-Z. Please substitute a default word in your language that can be written with those characters, substitute non-accented characters or leave it as "Hello!"'`

2018-08-08 15:10 UTC, chrisgarrity commented on src/extensions/scratch3_microbit/index.js
> +                        description: 'when a pin is connected to the micro:bit'
This is a difficult one to describe. I think we'll get better translations with a description like:
when the pin detects a connection to Earth/Ground

2018-08-08 15:15 UTC, technoboy10 commented on src/extensions/scratch3_microbit/index.js
> +                            })
Does that include punctuation like the exclamation point?

2018-08-14 16:19 UTC, chrisgarrity approved these changes
Thanks @technoboy10

2018-08-14 16:19 UTC, merged