Get param condition input
LLK/scratch-vm pull request #1563
Opened 2018-09-06 22:42 UTC by mzgoddard

### Resolves

Part of #1450.

### Proposed Changes

Pass parsing state information of the parent block's expectedArg. For getParam blocks ensure argument_reporter_boolean is used if the reporter is in a boolean input like CONDITION or a procedure call boolean input.

### Reason for Changes

scratch-blocks errors when a non-boolean reporter is in a boolean input. Like https://github.com/LLK/scratch-vm/pull/1562, this transforms "r" reporter blocks that Scratch 2 allows into "b" reporter blocks.

This even works for `getParam` blocks that are on scripts missing the procedure definition hat.

### Test Coverage

Loading http://localhost:8601/#10118230 works with this change.

2018-09-11 20:54 UTC, kchadha commented on src/serialization/sb2.js
> +            parentExpectedArg.inputName === 'CONDITION' ||
this check seems a little brittle, and it doesn't cover all our boolean cases (for example the not operator input is named OPERAND). The name doesn't actually prescribe the type information. Maybe we should add an additional property in the (sb2_specmap)[https://github.com/LLK/scratch-vm/blob/develop/src/serialization/sb2_specmap.js] for all the boolean inputs we know about? That seems like an approach that is more consistent with everything else we're doing for sb2 import.

2018-09-11 20:58 UTC, kchadha commented on src/serialization/sb2.js
> +            parentExpectedArg.inputName === 'CONDITION' ||
hmmm or actually....

I wonder if you can just get away with the following check `parentExpectedArg.type === 'input' && !parentExpectedArg.inputOp`

2018-09-11 21:18 UTC, kchadha requested changes
Information about expected boolean inputs should be encoded in the sb2_specmap as discussed in comments and discussions offline.

2018-09-13 16:55 UTC, mzgoddard commented
@kchadha Added explicit `boolean` and `substack` inputOp values to the input arguments missing a inputOp member. So all input arguments now have a defined inputOp value.

`boolean` and `substack` are specifically considered not to be shadow values, so the shadow block creation work skips them. And any input argument that may be later added without an inputOp value will log a warning when it is used.

2018-09-18 01:33 UTC, kchadha approved these changes
LGTM - Thanks for adding the warning for a missing `inputOp`!

2018-09-18 19:29 UTC, merged