Remove branding from translate extension
LLK/scratch-vm pull request #1569
Opened 2018-09-11 18:54 UTC by ericrosenbaum

- Remove block icon
- Remove the word "Google" from the extension name

2018-09-11 18:57 UTC, thisandagain requested changes

2018-09-11 18:57 UTC, thisandagain commented on src/extensions/scratch3_translate/index.js
> +const iconURI = '';
Could we just remove this (plus the `eslint` line above)?

2018-09-11 19:11 UTC, thisandagain approved these changes

2018-09-11 19:19 UTC, merged

2018-09-12 00:11 UTC, Kenny2github commented
May I ask why this change was necessary?