Fix locale-dependant string comparison operators to match 2.0
LLK/scratch-vm pull request #1593
Opened 2018-09-17 21:01 UTC by joker314

### Resolves

Resolves #1526

### Proposed Changes

Stop using the deceivingly similar `String.prototype.localeCompare`, as used in scratch-flash, because it behaves differently and inconsistently depending on the host environment, as specified by ECMAScript.

Inconsistency is bad -- it makes debugging hard

### Reason for Changes

scratch-flash used `s1.localeCompare(s2)`
scratch-vm was using `s1.localeCompare(s2)`

Despite them both being ECMAScript variants, the specification reads:

> The two Strings are compared in an implementation-defined fashion.

These implementations should take into account the locale.

> If no language-sensitive comparison at all is available from the host environment, this function may perform a bitwise comparison.

Browsers do take into account the user locale; but according to Adobe's documentation for ActionScript 3.0, it appears Flash always performs bit-wise comparisons.

> While this method is intended to handle the comparison in a locale-specific way, the ActionScript 3.0 implementation does not produce a different result from other string comparisons such as the equality (==) or inequality (!=) operators.

Since the two behave differently, serious backwards-compatibility issues were being filed, where equality wasn't working correctly. Therefore, the `compare()` function is modified such that it uses bitwise comparisons.

### Test Coverage

No automatic tests are added. Manual tests were performed, these were:
- [X] a < z (true)
- [X] z < a (false)
- [X] b = b (true)
- [X]あ = ア (false) in the Japanese locale

Resource for changing Firefox's language: https://support.mozilla.org/en-US/kb/use-firefox-interface-other-languages-language-pack

2018-09-18 08:25 UTC, apple502j commented
Looks very good to merge!

2018-09-18 11:19 UTC, towerofnix commented
>Finally, locale-dependant outputs to blocks allows projects to selectively show harassing messages like 'I don't like people from country X'.

This is a moot point, unfortunately, because the Translate extension has a "language" block. But otherwise this PR looks good!

2018-09-18 15:50 UTC, joker314 commented
I've tried to test that localeCompare wasn't being used by testing `a < b` and then doing:

```javascript
    // eslint-disable-next-line no-extend-native
    String.prototype.localeCompare = () => 0;
```

In the unit test. It still passed. I feel that to perform this test, some hacky code will need to be used. I've decided to stop looking into it for now.

2018-09-25 18:26 UTC, kchadha commented
@joker314 Thanks for submitting this pull request! We will take a look at these changes soon.

2018-10-04 18:33 UTC, thisandagain requested changes
This looks reasonable. My only major reservation / recommendation is to expand the scope of the unit tests to include the `あ = ア` case that this PR claims to be resolving. Once the test coverage is expanded I think this will be good to merge.

2018-10-04 18:38 UTC, merged

2018-10-04 19:23 UTC, joker314 commented
Note that the unit test `あ = ア` isn't too useful in this case: this bug only occurs when the browser language is set to Japanese (and unit tests will probably run on English-language computers). We should instead test that the `localeCompare` method isn't used, if we want to bother testing for it at all.