Monitor save & load
LLK/scratch-vm pull request #1686
Opened 2018-10-21 22:46 UTC by kchadha

### Resolves

Resolves #1513 
Resolves #1628
Adds ability to save and load monitors, one of the issues mentioned in LLK/scratch-gui#3086

### Proposed Changes

- Serialize monitor information when saving a project.
- Deserialize monitor information when loading an sb3 (this adds a new monitor record to the runtime monitor state and augments the block container blocklyListen function to set the `isMonitored` and `targetId` properties on the appropriate monitor block when it gets created).
- Resolves an issue with monitor blocks where stage/non-target-specific monitors (e.g. loudness and timer) weren't getting imported correctly because the monitor blocks existed before the projects were loaded, and the sb2 was trying to create the monitor block again from scratch with the monitor properties specified above. However, calling the `createBlock` function from `src/engine/blocks.js` on a block id that already exists in the block container results in an early exit of the function, which meant that the existing block was not getting updated with the required monitor properties.

#### Known Issues
- Along the lines of the above bullet, I realized that the monitor blocks will either already exist in the runtime `monitorBlocks` blocks container, so they don't need to be created from scratch in the sb2 or sb3 importers. However, I wasn't able to remove the block creation logic from the sb2 importer because it was needed for the call to the `_getBlockParams()` from `src/engine/blocks.js`. A future fix for this issue might include initially adding the new monitor record with `null` for the `params` property and updating it after the appropriate monitor block gets created. 
- Imported variable monitors still don't display the correct checkbox state in the toolbox. The toolbox state becomes in-sync again after switching to a different sprite or tab causing the workspace and toolbox to reload.
- Monitor information is not currently serialized when exporting a sprite. This was left out of this PR because there is currently still a problem with variables retaining their IDs when serialized and thus importing a sprite3 with local variables (and monitors) back into the project it was exported from causes the local variable IDs to no longer be unique. This creates confusion with the local variable monitors because the monitor block is identified by the variable ID (thus two variables share the same monitor and cannot be displayed at the same time).

### Reason for Changes

Monitors should get saved and loaded in sb3s.

### Test Coverage

Manual testing along with LLK/scratch-gui#TBD.

Ensure the following:
- [ ] Can still import monitors from 2.0 projects
- [ ] Stage monitors like `loudness` and `timer` load correctly, (are visible, not empty, and update)
- [ ] Imported monitors retain position and mode
- [ ] Can save and load monitors in .sb3 projects. Monitors should load correctly and should update with changes to their values.

### Related PRs

- This PR is related to LLK/scratch-gui#TBD. This PR should be merged before the GUI PR.

2018-10-23 14:39 UTC, paulkaplan requested changes
Looks like we should add an integration test for loading sb3 files saved with monitors, to parallel the one testing loading sb2 files with monitors

2018-10-23 14:41 UTC, paulkaplan commented on src/serialization/sb2.js
> +    // when the target is installed because the toolbox will reload.
Make sure to check this works in player mode where there is no toolbox

2018-10-23 15:15 UTC, kchadha commented
As discussed offline, it looks like this approach of using the monitor block from the runtime monitorBlocks container is not going to work after all since we won't always have monitorBlock information when we need it. In player mode (thus also on the preview page), the toolbox doesn't get loaded when the project does, so the monitorBlocks container does not get populated and monitors appear empty when a project is loaded.

#### Possible Solutions for The Future™️

- Extension-ify just the monitor blocks (is this possible)? Specifically they have a handy json serialization function and a minimal specification
- SB3 -> SB3 specmap (for just the monitor blocks?). Extension monitors would still use their json serialization function
- Serialize the actual monitor blocks as well as the monitor record in the sb3. We would need to check how much this ends up bloating the file size.

2018-10-23 15:45 UTC, kchadha commented
Closing this until I can come back to it in the future.

2018-11-13 20:09 UTC, paulkaplan commented on src/serialization/sb3.js
> +        // If a monitor block doens't already exist for this monitor,
nit: typo "doens't"

2018-11-13 20:13 UTC, paulkaplan commented on src/serialization/sb3.js
> +    // Otherwise, the monitor block will get created when the toolbox updates
Does this comment still apply?

2018-11-14 12:28 UTC, paulkaplan approved these changes
Apart from the nit and question, looks good.

2018-11-14 18:16 UTC, kchadha commented on src/serialization/sb3.js
> +    // Otherwise, the monitor block will get created when the toolbox updates
No it doesn't =]. Removed.

2018-11-14 18:16 UTC, kchadha commented on src/serialization/sb3.js
> +        // If a monitor block doens't already exist for this monitor,
Fixed

2018-11-14 18:23 UTC, merged