Handle unknown opcode in input
LLK/scratch-vm pull request #1716
Opened 2018-10-31 21:48 UTC by spectranaut

### Resolves

https://github.com/LLK/scratch-vm/issues/1682

### Proposed Changes

Fix issue where a block has an input of unknown opcodes, was causing an import error.

### Reason for Changes

#1254 skips unknown opcodes when importing blocks from sb2 projects. However, that PR missed the case where an input is undefined. This PR fixes projects that were failing to load because of that issue.

### Test Coverage

This is my first issue, I'm not sure how to test other than manually with this project: https://llk.github.io/scratch-gui/develop/#116599254

### How to test this

1. In Scratch 2.0, drag out a block with an input
2. Put a block with unknown opcodes in the input. Examples are the "picoboard" extension blocks, such as "sensor value"
3. Import the project into 3.0
4. The project should be able to load and there will be a default value (shadow) instead of the input. There should be warnings about skipped opcodes in the console.

2018-11-14 19:16 UTC, kchadha requested changes
A few minor comments, and then it's good to go!

2018-11-14 19:16 UTC, kchadha commented on src/serialization/sb2.js
> +
Nit: stray newline

2018-11-14 19:16 UTC, kchadha commented on src/serialization/sb2.js
> +                shadowObscured = true;
You should move this line below the `if (innerBlocks.length > 0)` block below since it's not being used till later

2018-11-14 19:25 UTC, spectranaut commented
addressed your feedback, @kchadha ! :)

2018-11-15 15:07 UTC, kchadha approved these changes
LGTM!

2018-11-15 15:09 UTC, merged