Clear the pen layer when runtime dispose happens.
LLK/scratch-vm pull request #1815
Opened 2018-12-04 21:44 UTC by paulkaplan

### Resolves

_What Github issue does this resolve (please include link)?_

Resolves https://github.com/LLK/scratch-gui/issues/1850

### Proposed Changes

_Describe what this Pull Request does_

Add a RUNTIME_DISPOSED event that the pen extension listens for and clears the pen layer when it occurs. 

No attempt is made in this PR to unload the extension blocks or anything like that.

2018-12-04 23:49 UTC, kchadha commented on test/unit/engine_runtime.js
> +    rt.start();
```suggestion
    rt.dispose();
```

2018-12-04 23:50 UTC, kchadha commented on test/unit/engine_runtime.js
> +    rt.start();
I tried to commit the above suggestion but turns out I don't have permission to push to your fork...

2018-12-04 23:51 UTC, kchadha requested changes
Failing test, but after that LG.

2018-12-05 14:02 UTC, paulkaplan commented
Thanks for that! I was being too hasty! Included your suggestion.

2018-12-05 15:58 UTC, kchadha approved these changes
LGTM

2018-12-05 17:30 UTC, merged