Remove Unicode Backspace from XML to prevent broken SVG
LLK/scratch-vm pull request #1883
Opened 2018-12-31 13:50 UTC by yokobond

### Resolves

Fix of #1873 Unicode 'BACKSPACE' stop to read project

### Proposed Changes

Remove the problematic character at the process to make XML source that build SVG graphics.

### Reason for Changes

The character '\0008' breaks SVG so that it should not be used but it will input in any text field accidentally by users. V2.0 accept the char and no probrem to read and convert to V3.0 which project including it. Removing the char at the last process to make SVG will fix the both problems.  The escape XML will good place to do this. 

### Test Coverage

New unit-test was added for xmlEscape().

2019-01-01 17:16 UTC, thisandagain commented
/cc @kchadha @ktbee @fsih @rschamp

2019-01-06 22:30 UTC, kchadha requested changes
@yokobond, unfortunately this fix does not work. Pulling in these changes and testing with the project in the original issue (273360075) shows errors in the console.

You are right about the fix being related to what can and cannot be displayed in XML/SVG, but unfortunately fixing the problem fully will need a lot more changes. I am currently working on a fix for a related issue (#1077), and so hopefully this issue will get resolved with that fix as well.

2019-01-07 04:10 UTC, towerofnix commented
Would this change prevent projects that intentionally detect the backspace character from functioning correctly? We want to be able to load this projects - but not at the expense of them running as they're intended to, right? (Same type of reasoning as in #1882.) Or does this just change how the block displays, but not how it saves in the sb3 (i.e. is the backspace character still present in the sb3 json)?

2019-01-07 18:41 UTC, kchadha commented
@towerofnix, with this change, the backspace control character is still saved in the sb3 json.

2019-01-24 03:46 UTC, closed without merging