Re enable tests that were unavailable during maintenance
LLK/scratch-vm pull request #1898
Opened 2019-01-07 18:01 UTC by paulkaplan

/cc @kchadha @rschamp

2019-01-07 22:28 UTC, kchadha requested changes
This also enables a test that was being skipped from before maintenance -- the util_task_queue test. That one was being skipped because it's a flaky test.

2019-01-07 22:28 UTC, kchadha commented on test/unit/util_task-queue.js
> +const test = require('tap').test;
```suggestion
const test = require('tap').skip;
```

2019-01-08 18:29 UTC, paulkaplan commented on test/unit/util_task-queue.js
> +const test = require('tap').test;
Gotchya thanks

2019-01-08 18:40 UTC, kchadha approved these changes
LGTM

2019-01-08 18:45 UTC, merged