Variables Extension Monitors
LLK/scratch-vm pull request #2262
Opened 2019-08-15 20:03 UTC by kchadha

### Proposed Changes

- Make variable/list monitors work with the new variables extension.
    - Variable reporter blocks in the toolbox were getting random IDs assigned to them, and these ids were getting newly generated every time we refreshed the toolbox. This makes it impossible to have the block monitor stay associated with the toolbox block. Add `paletteKey` property to dynamic extension block info to keep a block id consistent.
     - When a variable or list is created from `make a variable` button, it should have its monitor checkbox checked. This was previously handled automatically by scratch-blocks, but with the new extension code paths, the variable block does not exist at the time when we have submitted the information in the modal. The VM needs to hold on to the variable creation information when it receives a `var_create` event from scratch-blocks and keep track that there is a monitor pending for a block with the same id as the variable. This pending monitor is used to later add the check to the monitor checkbox for the newly created variable reporter block.
    - Monitor label information (e.g. label text and monitor color) for extension monitors are now compatible with dynamic extension blocks as well as core extensions. The information returned about the monitor is now its label and color instead of its label and a string representing a category from which to derive color information from. The block color of the block being monitored is used directly instead.
- Sorts the variable reporters and the variables/lists (in the block dropdowns) alphabetically.

### Related PRs
This PR is related to LLK/scratch-gui#TBD. This PR should go in first.

2019-09-09 07:13 UTC, cwillisf requested changes
Looks good overall! There are a couple minor questions and things but generally 👍

2019-09-09 07:13 UTC, cwillisf commented on src/engine/blocks.js
> +                this.runtime.addPendingMonitor(e.varId);
Is it possible to get here without a paired `removePendingMonitor` call? If so, would that cause problems with a future project load or anything like that?

EDIT: Ah, looks like you take care of it in the runtime's `dispose` method. I'll leave this here in case you have further comment but it looks OK to me.

2019-09-09 07:13 UTC, cwillisf commented on src/engine/runtime.js
> +    getMonitorLabelForBlock (id) {
👍 on the new name

2019-09-09 07:13 UTC, cwillisf commented on src/engine/runtime.js
> +            color: categoryInfo.color1, // TODO This assumes that all extensions have the same monitor color.
This TODO is now incorrect

2019-09-09 07:13 UTC, cwillisf commented on src/engine/runtime.js
> +        this._pendingMonitors[blockId] = true;
If you're feeling fancy you could use [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) instead

2019-09-09 07:13 UTC, cwillisf commented on src/util/string-util.js
> +    // Port over the string comparison utiliy from scratch-blocks
typo: utility

2019-09-12 19:01 UTC, kchadha commented
@cwillisf, addressed the PR review comments!

2019-09-16 21:46 UTC, cwillisf approved these changes
👍

2019-09-17 15:53 UTC, merged