Add NPM Script 'build'
LLK/scratch-vm pull request #242
Opened 2016-10-05 00:25 UTC by TheBrokenRail

2016-10-05 01:05 UTC, liam4 commented on package.json
> +    "start": "webpack --colors --progress",
*Two* `start` properties?

2016-10-05 17:31 UTC, rschamp commented
Hi @TheBrokenRail — this PR is a bit confusing to me.  Would you please fill out the Pull Request template I added to the description?  Thanks!

2016-10-07 22:13 UTC, TheBrokenRail commented
Changed Description

2016-10-08 17:20 UTC, TheBrokenRail commented
Any Comments?

2016-10-11 06:02 UTC, dekrain commented on package.json
> +    "start": "webpack --colors --progress",
I think it should be `start` and `build`

2016-10-11 15:41 UTC, rschamp requested changes
It seems that the goal of this PR is not only to add the script build, but to make `package.json` usable under Windows.

@cwillisf In other repos that use Makefiles, e.g. https://github.com/LLK/scratch-render how do you run them?

2016-10-11 15:41 UTC, rschamp commented on package.json
> +    "start": "webpack --colors --progress",
Like @dekrain said, this doesn't add the script `build`, it adds a second `start` script which makes this invalid JSON. Please update to `build`.

2016-10-13 01:40 UTC, TheBrokenRail commented
Fixed Second Start Bug

2016-10-13 01:56 UTC, TheBrokenRail commented on package.json
> +    "start": "webpack --colors --progress",
Fixed!

2016-10-13 05:54 UTC, dekrain approved these changes

2016-10-13 13:35 UTC, rschamp approved these changes
@TheBrokenRail Looks good, thanks! Thanks for bringing up the issues with running `make` on Windows.

2016-10-13 13:35 UTC, merged

2016-10-13 19:10 UTC, cwillisf commented
@rschamp I usually use Cygwin to deal with Scratch-related repositories, and I make sure my installation of Cygwin has GNU Make and all the other tools that our repositories require.

There are other options which might be more common, though. You can install Node.js by itself and end up without Bash, let alone Make. You can also install [Git for Windows](https://git-for-windows.github.io/) which gets you Bash but not Make. It's also worth noting that Git for Windows uses MSYS rather than Cygwin, so there are a few differences including path conventions. You can install GNU Make on MSYS, but those who are just interested in Node-style development usually don't.

Long story short, I do think it would be more friendly to Windows users if we worked on requiring fewer pre-installed tools. Ideally we could get it down to requiring only `npm` and things installed by `npm`, like Webpack.

2016-10-13 21:11 UTC, rschamp commented
@cwillisf Thanks for the background! We took a crack at using npm only, and no Makefile in https://github.com/LLK/scratch-audioengine/