Implement say block
LLK/scratch-vm pull request #266
Opened 2016-10-13 20:09 UTC by dekrain

# Important
Merge this after scratch-render:#49

2016-10-13 20:19 UTC, CosmicWebServices commented
I think they have to have a design discussion about this...

2016-10-13 20:24 UTC, dekrain commented
But of rendering side

2016-10-13 20:27 UTC, CosmicWebServices commented
Yeah

2016-10-14 01:09 UTC, tmickel requested changes

2016-10-14 01:09 UTC, tmickel commented on src/sprites/clone.js
> +    if (this.isStage || !this.render) {
do you mean `this.renderer`? I can't imagine this would work as I don't think such a variable exists?

2016-10-14 01:09 UTC, tmickel commented on src/sprites/clone.js
> +        this.bubble = this.render.renderBubble(this.drawableID, message);
Let's leave the `console.log` for `type === 'think'`.

2016-10-14 08:50 UTC, dekrain commented
Done!

2016-10-14 17:11 UTC, tmickel commented
As you said, this can't be merged until there is support in the renderer.

2016-10-14 17:15 UTC, dekrain commented
But you can approve changes and label this ;)

2016-10-14 17:21 UTC, tmickel commented
Once we work out the implementation for the renderer :) We'll typically label things as "pr - good to merge" when merging the PR will leave the project in a usable state - i.e., there are no further dependencies.

2016-10-26 14:39 UTC, tmickel commented
Hi @dekrain,
I'm going to close this for now, can re-open once we land the say bubble in the renderer and finalize that API. Thanks again for taking the first try at it.

2016-10-26 14:39 UTC, closed without merging