Add days since 2000 block
LLK/scratch-vm pull request #272
Opened 2016-10-14 17:46 UTC by CosmicWebServices

Look at #268 for more info

2016-10-14 17:46 UTC, dekrain requested changes

2016-10-14 17:46 UTC, dekrain commented on src/blocks/scratch3_sensing.js
>  };
Add empty line here

2016-10-14 17:47 UTC, dekrain commented on src/blocks/scratch3_sensing.js
> +}
Semicolon here

2016-10-14 17:48 UTC, dekrain commented on src/blocks/scratch3_sensing.js
> +  var start = new Date(2000, 1-1, 1);
4 spaces instead of 2

2016-10-14 17:50 UTC, CosmicWebServices commented
OK I fixed the problems

2016-10-14 17:50 UTC, dekrain commented
One thing up

2016-10-14 17:50 UTC, CosmicWebServices commented
? @dekrain

2016-10-14 17:51 UTC, CosmicWebServices commented on src/blocks/scratch3_sensing.js
>  };
I think I fixed tat

2016-10-14 17:52 UTC, CosmicWebServices commented
Why is it failing?

2016-10-14 17:52 UTC, dekrain commented
Fine.

2016-10-14 17:53 UTC, dekrain requested changes

2016-10-14 17:53 UTC, dekrain commented on src/blocks/scratch3_sensing.js
> +
No here.

2016-10-14 17:53 UTC, dekrain commented on src/blocks/scratch3_sensing.js
> +  var start = new Date(2000, 1-1, 1);
4 spaces instead of 2

2016-10-14 17:53 UTC, CosmicWebServices commented on src/blocks/scratch3_sensing.js
> +  var start = new Date(2000, 1-1, 1);
What does that mean?

2016-10-14 17:55 UTC, CosmicWebServices commented on src/blocks/scratch3_sensing.js
> +  var start = new Date(2000, 1-1, 1);
Oh wait now I know

2016-10-14 17:55 UTC, dekrain commented on src/blocks/scratch3_sensing.js
> +  var start = new Date(2000, 1-1, 1);
You used:
```
  ...
^2 spaces
instead of
    ...
^4 spaces
```

2016-10-14 17:55 UTC, liam4 commented on src/blocks/scratch3_sensing.js
> +  var start = new Date(2000, 1-1, 1);
Probably to indent it like this: `****` (where each `*` is a space) instead of like this: `**`.

2016-10-14 17:56 UTC, CosmicWebServices commented
Sorry about the problems this is my first pr I did

2016-10-14 17:57 UTC, dekrain commented
No fine. But line 28 is unnecessary

2016-10-14 17:59 UTC, dekrain commented
Correct.

2016-10-14 18:00 UTC, CosmicWebServices commented
Thanks!

2016-10-14 18:13 UTC, dekrain commented
16 comments in 15 minutes? New record?

2016-10-14 18:18 UTC, CosmicWebServices commented
Totaly

2016-10-17 13:46 UTC, CosmicWebServices commented
Can this be checked?

2016-10-17 15:59 UTC, tmickel requested changes

2016-10-17 15:59 UTC, tmickel commented on src/blocks/scratch3_sensing.js
> +    return (today.valueOf() - start.valueOf()) / 1000 / 86400;
Hey @CosmicWebServices,

Thanks for taking this on!

What about the timezone code we discussed in #268? It looks to me like JavaScript supports `getTimezoneOffset`, so we could adjust to UTC just like scratch-flash.

2016-10-17 15:59 UTC, tmickel commented on src/blocks/scratch3_sensing.js
> +    var start = new Date(2000, 1-1, 1);
1-1 == 0?

2016-10-17 15:59 UTC, tmickel commented on src/blocks/scratch3_sensing.js
> +    var today =   new Date();
Looks like you have some extra space here before the `new`.

2016-10-17 16:33 UTC, CosmicWebServices commented on src/blocks/scratch3_sensing.js
> +    return (today.valueOf() - start.valueOf()) / 1000 / 86400;
Changed the whole thing so that it is exactly like it is in scratch 2

2016-10-17 16:39 UTC, dekrain requested changes

2016-10-17 16:39 UTC, dekrain commented on src/blocks/scratch3_sensing.js
> +    return mSecsSinceStart / msPerDay;
I know in Scratch 2.0 value is float, but I think here, in Scratch 3.0, it can be `Math.floor(...)`

2016-10-17 16:47 UTC, CosmicWebServices commented on src/blocks/scratch3_sensing.js
> +    return mSecsSinceStart / msPerDay;
@tmickel what do u think

2016-10-17 16:54 UTC, CosmicWebServices commented on src/blocks/scratch3_sensing.js
> +    var start = new Date(2000, 1-1, 1);
Yeah for some reason it works that way

2016-10-17 16:55 UTC, CosmicWebServices commented on src/blocks/scratch3_sensing.js
> +    var today =   new Date();
Whoops

2016-10-17 17:57 UTC, tmickel approved these changes
Looks good to me, thanks again @CosmicWebServices and @dekrain!

2016-10-17 17:57 UTC, merged

2016-10-17 18:07 UTC, CosmicWebServices commented
YAY!!! MY FIRST PR WAS MERGED!

2016-10-17 18:12 UTC, dekrain commented
:clap: :clap: :clap: :clap:

2016-10-26 14:22 UTC, tjvr commented on src/blocks/scratch3_sensing.js
> +    var start = new Date(2000, 1-1, 1);
I'm confused, too. How would using `0` here be any different?

2016-10-26 14:24 UTC, tmickel commented on src/blocks/scratch3_sensing.js
> +    var start = new Date(2000, 1-1, 1);
Somehow missed this before I merged it - will fix.