Extremely WIP Implementation Of Custom Reporters
LLK/scratch-vm pull request #332
Opened 2016-11-13 18:04 UTC by TheBrokenRail

### Proposed changes

_Adds Code for custom reporters_

### Untested Due To No Scratch-Blocks Implementation

2016-11-13 18:37 UTC, dekrain requested changes

2016-11-13 18:37 UTC, dekrain commented on src/blocks/scratch3_procedures.js
> +        this.thread = this.thread + 1;
```JavaScript
this.thread++;
```

2016-11-13 18:37 UTC, dekrain commented on src/blocks/scratch3_procedures.js
>          for (var i = 0; i < paramNames.length; i++) {
...and here.

2016-11-13 18:37 UTC, dekrain commented on src/engine/execute.js
> +            thread.stackFrames[0].executionContext.return = value;
```JavaScript
currentStackFrame.executionContext.return = value;
```

2016-11-13 19:50 UTC, dekrain commented
`src/engine/execute.js#231`:
```javascript
currentStackFrame.executionContext.return = value;
```

2016-11-13 21:48 UTC, TheBrokenRail commented on src/engine/execute.js
> +            thread.stackFrames[0].executionContext.return = value;
Wouldn't that cause the value to be set to the report block instead of the top block (hat)

2016-11-13 22:18 UTC, dekrain commented on src/engine/execute.js
> +            thread.stackFrames[0].executionContext.return = value;
So why you added

``` JavaScript
for (; k < this.runtime.threads[k].stackFrames.length; k++)
```

?

2016-11-14 00:05 UTC, TheBrokenRail commented on src/engine/execute.js
> +            thread.stackFrames[0].executionContext.return = value;
That runs from the calling block and not the hat block so it has to "find" the stackFrame

2016-11-14 15:44 UTC, dekrain commented on src/engine/execute.js
> +            thread.stackFrames[0].executionContext.return = value;
Shouldn't it be

``` JavaScript
var stack = this.runtime.threads[k].stackFrames[0];
```

?

2016-12-28 21:47 UTC, CosmicWebServices commented
@TheBrokenRail you should finish this

2016-12-28 22:21 UTC, TheBrokenRail commented
I can't test this until the scratch blocks PR is merged

2016-12-28 22:43 UTC, liam4 commented
You can probably figure out how to get a local copies of scratch-blocks and scratch-vm to work together, but I don't know if there's any official documentation on that.

2017-01-06 20:19 UTC, TheBrokenRail commented
I will close this until a design for implementation is more finalized and testable.

2017-01-06 20:19 UTC, closed without merging