Fix for the "Empty or white space strings equal 0" bug
LLK/scratch-vm pull request #438
Opened 2017-02-08 08:40 UTC by griffpatch

See: Empty or white space strings equal 0 #435

2017-02-09 13:14 UTC, thisandagain requested changes

2017-02-09 13:14 UTC, thisandagain commented on src/util/cast.js
> +    if (n1 === 0 && (v1 == null || typeof v1 === 'string' && v1.trim().length === 0)) {
This string of comparators should probably be moved out into it's own `util/cast` method for the sake of readability, reusability, and testing. Perhaps we could call it simply `isEmpty` and then amend the unit test suite for `compare` and add test coverage for `isEmpty`?

2017-02-09 13:49 UTC, griffpatch commented
Problem is... function calls are mega expensive when is the core runtime
code... You really want to avoid pulling things out into functions if
possible in my experience. I was very careful with my choice of comparators
here to make it as quick as possible given the key location it is being
used here? I do agree it would be nice to pull out if you could assume
javascript would re-inline it again... but in my experience it hasn't been
doing that :(

You still want me to do it?

On 9 February 2017 at 13:15, Andrew Sliwinski <notifications@github.com>
wrote:

> Assigned #438 <https://github.com/LLK/scratch-vm/pull/438> to @griffpatch
> <https://github.com/griffpatch>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/LLK/scratch-vm/pull/438#event-955542898>, or mute the
> thread
> <https://github.com/notifications/unsubscribe-auth/AGbNvsy3W9j_lENTe6--QUGSVtl-sacnks5raxFYgaJpZM4L6hpE>
> .
>

2017-02-09 14:42 UTC, griffpatch commented
I was wondering, I know you are currently building and running off the
non-minimized javascript for ease of debugging... Are there settings in the
build scripts to auto inline things like this (in the production build)
such that breaking it out into a function will not in the end impact the
speed of execution but instead be exactly the same? *hopeful expression*.
If this was the case it would make a big difference to how I went about
coding in these repositories?

On 9 February 2017 at 13:48, Andrew Griffin <andy@griffpatch.co.uk> wrote:

> Problem is... function calls are mega expensive when is the core runtime
> code... You really want to avoid pulling things out into functions if
> possible in my experience. I was very careful with my choice of comparators
> here to make it as quick as possible given the key location it is being
> used here? I do agree it would be nice to pull out if you could assume
> javascript would re-inline it again... but in my experience it hasn't been
> doing that :(
>
> You still want me to do it?
>
> On 9 February 2017 at 13:15, Andrew Sliwinski <notifications@github.com>
> wrote:
>
>> Assigned #438 <https://github.com/LLK/scratch-vm/pull/438> to @griffpatch
>> <https://github.com/griffpatch>.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/LLK/scratch-vm/pull/438#event-955542898>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe-auth/AGbNvsy3W9j_lENTe6--QUGSVtl-sacnks5raxFYgaJpZM4L6hpE>
>> .
>>
>
>

2017-02-09 14:42 UTC, thisandagain commented
I do. At least in the case of Chrome (v8) and Firefox (Gecko) we can be fairly certain that the JS runtime will optimize and memoize the function call for something like this. For now I'd rather err towards readability, maintenance, and test coverage than performance optimization though I do certainly appreciate that we need to find a balance between the two.

2017-02-09 14:45 UTC, thisandagain commented
> build scripts to auto inline things like this (in the production build)
such that breaking it out into a function will not in the end impact the
speed of execution but instead be exactly the same

Good question. Not that I know of. Most webpack plugins (like UglifyJS) are more about compression than optimization. Most optimization of this type happens within each vendor's JS runtime implementation.

2017-02-09 14:48 UTC, griffpatch commented
Just I've noticed when using the profiler in chrome that the most simple
function calls that do pretty much nothing except return values still
execute faster if they are inlined...  I'll do some benchmarking on the
change and see what impact it has before I re-commit... Might have to wait
until tomorrow.

Thanks

On 9 February 2017 at 14:45, Andrew Sliwinski <notifications@github.com>
wrote:

> build scripts to auto inline things like this (in the production build)
> such that breaking it out into a function will not in the end impact the
> speed of execution but instead be exactly the same
>
> Good question. Not that I know of. Most webpack plugins (like UglifyJS)
> are more about compression than optimization. Most optimization of this
> type happens within each vendor's JS runtime implementation.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/LLK/scratch-vm/pull/438#issuecomment-278661930>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AGbNvnRsEi5rjpf6-KHP_c5wgEqgRPlQks5rayaUgaJpZM4L6hpE>
> .
>

2017-02-09 14:53 UTC, thisandagain commented
One of my favorite tools for testing things like this is [jsperf.com](https://jsperf.com/)

2017-02-09 14:56 UTC, griffpatch commented
Yes, I did use a few examples on there to try things out... but I think
because of the way webpack packages the classes things are not quite as
simple as they appear when taken on their own... However, it's a great way
to test simple things :)

On 9 February 2017 at 14:54, Andrew Sliwinski <notifications@github.com>
wrote:

> One of my favorite tools for testing things like this is jsperf.com
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/LLK/scratch-vm/pull/438#issuecomment-278664658>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AGbNvhg_LTwjq9giToUOHLG5hjJImk6sks5rayiIgaJpZM4L6hpE>
> .
>

2017-02-09 15:02 UTC, thisandagain commented
Yup. This is one of the reasons I've been a little hesitant to move the VM over to ES6 as adding Babel to the build process will add yet another layer of indirection.

2017-02-09 15:19 UTC, griffpatch commented
Is Babel just a convertor from the yet to be fully implemented ES6 back to
ES5?

On 9 February 2017 at 15:02, Andrew Sliwinski <notifications@github.com>
wrote:

> Yup. This is one of the reasons I've been a little hesitant to move the VM
> over to ES6 as adding Babel to the build process will add yet another layer
> of indirection.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/LLK/scratch-vm/pull/438#issuecomment-278667579>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AGbNvjrsmt99Dyum1ficLIzob29m4-Y6ks5rayqUgaJpZM4L6hpE>
> .
>

2017-02-09 15:22 UTC, thisandagain commented
Yup, but it includes a series of plugins which can modify the source a fair amount and sometimes lead to indirection (particularly when dealing with performance optimization) IME.

2017-02-09 15:29 UTC, griffpatch commented
Is the scratch-render using this already? I noted it had the 'const' and
'let' keywords and class declaration... but the debugging of those
javascript files had reverted back to ES5...

On 9 February 2017 at 15:22, Andrew Sliwinski <notifications@github.com>
wrote:

> Yup, but it includes a series of plugins which can modify the source a
> fair amount and sometimes lead to indirection (particularly when dealing
> with performance optimization) IME.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/LLK/scratch-vm/pull/438#issuecomment-278673627>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AGbNvivUhZfgEh8xmupmSjBVTr29Hj0Eks5ray9TgaJpZM4L6hpE>
> .
>

2017-02-09 15:38 UTC, thisandagain commented
Yes. `scratch-render` uses ES6 / Babel:
https://github.com/LLK/scratch-render/blob/develop/webpack.config.js#L24

2017-02-10 08:08 UTC, griffpatch commented
Ok, I've amended this pull request as you requested. The good news is that it doesn't appear to slow things down in the slightest! In fact it's debatably slightly faster which (very very bad timing using project #144580026). But it gives a gist which is useful in these things. Problem is the variance can be huge. Anyhow, it's no big performance issue either way so I'm quite happy with that.

2017-02-10 13:29 UTC, thisandagain approved these changes

2017-02-10 13:30 UTC, thisandagain commented
Looks good. Thanks.

2017-02-10 13:30 UTC, merged