Default bitmapResolution to 1 if not provided in costume metadata
LLK/scratch-vm pull request #485
Opened 2017-03-01 17:10 UTC by thisandagain

### Resolves

Resolves GH-484

### Proposed Changes

Default `bitmapResolution` to `1` if no value is provided in the costume metadata.

### Reason for Changes

Many sprites in the sprite library (e.g. "Apple") do not specify a `bitmapResolution` in their costume metadata. This leads to a bug in the GUI when one of these sprites is added to the project where the sprite is not rendered to the screen.

Example: 
https://github.com/LLK/scratch-gui/blob/develop/src/lib/libraries/sprites.json#L569

2017-03-01 17:15 UTC, thisandagain commented
@rschamp Tests are failing due to issues with `./test/unit/util_filter-toolbox.js` not this PR.

2017-03-01 18:22 UTC, rschamp requested changes
I think it would be more robust if this default were set in `RenderedTarget`, or even in the renderer's handling of costumes. For instance, if a bitmap costume is added without a `bitmapResolution` (rather than a sprite containing a costume without `bitmapResolution`), this same problem will arise from a different place.

2017-03-02 00:51 UTC, thisandagain commented
@rschamp This is ready for re-review

2017-03-02 16:19 UTC, rschamp approved these changes
Looks great, thanks!

2017-03-02 16:21 UTC, merged