Load projects & costumes through scratch-storage
LLK/scratch-vm pull request #498
Opened 2017-03-09 19:41 UTC by cwillisf

NOTE: the scratch-storage module should be made public before merging this PR.

### Resolves

Resolves #427

### Proposed Changes

This change adds scratch-storage as a dependency and modifies the SB2 import process to use scratch-storage. Costumes and the project JSON are fully working, but sound loading is not yet finished. For now, sounds are still working through the old path.

Because costumes are now loaded through scratch-storage, scratch-render no longer needs to make its own HTTP requests.

There are a few other, smaller changes in here, including:
- Use the `Scratch` namespace for "global" items in the playground when possible
- Alphabetize Scratch dependencies (audio, render, storage)
- Fixed `parseScratchObject` returning `undefined` when it should return `null`

### Reason for Changes

File access should be centralized in scratch-storage.

### Test Coverage

Existing tests which interact with project or costume data effectively cover these changes.

2017-03-09 23:59 UTC, cwillisf commented
I believe this PR is now ready for review -- the initial submission had broken tests.
It's still not ready to _merge_ until the storage module is public, of course. Coming soon!

2017-03-10 19:09 UTC, rschamp commented on src/import/sb2import.js
> +    var promise = runtime.storage.load(assetType, md5);
If you don't attach storage to your VM, this line throws a `TypeError`... at the top of these functions that require `runtime.storage`, maybe we should log a warning and exit before doing anything.

2017-03-23 22:44 UTC, rschamp requested changes

2017-03-23 22:44 UTC, rschamp commented on src/import/sb2import.js
> +        log('No storage module present; cannot load costume asset: ', md5ext);
I think it would be more appropriate for these to be errors (with `log.error`).

2017-03-23 23:49 UTC, rschamp approved these changes
🎉

2017-03-24 05:10 UTC, merged