Use Scratch Storage to load sounds and Audio Engine to decode and register them
LLK/scratch-vm pull request #512
Opened 2017-03-27 16:04 UTC by ericrosenbaum

### Resolves

Addresses https://github.com/LLK/scratch-vm/issues/511

### Proposed Changes

Remove call to loadSounds from rendered-target. Scratch Storage loads the sounds, and passes the data to the audio engine to decode and register them. 

### Reason for Changes

Moving all asset loading to Scratch Storage.

### Test Coverage

No tests yet.

2017-03-29 14:59 UTC, cwillisf requested changes

2017-03-29 14:59 UTC, cwillisf commented on src/import/sb2import.js
> +        log('No audio engine present; cannot load sound asset: ', sound.md5);
These changed to `log.error` as part of the review process on #498 so I'd recommend changing this one too

2017-03-29 17:49 UTC, cwillisf approved these changes

2017-03-31 13:15 UTC, rschamp approved these changes

2017-03-31 15:10 UTC, merged