Use costume loading from importer in public costume and backdrop loader
LLK/scratch-vm pull request #514
Opened 2017-03-27 19:09 UTC by paulkaplan

Extracts the costume loader from the importer so that it can be used for both importing and adding costume/backdrop through the public APIs.

Some background:
Before scratch-storage, we used to just tack on the costume URL directly to the costume object, allowing it to be loaded by the renderer. Now that loading is happening with scratch-storage, the loading step is explicit, and wasn't available to the public API, meaning the backdrop / costume library wouldn't work. This, along with a corresponding PR to scratch-gui, fixes that.

2017-03-27 19:23 UTC, rschamp commented on src/import/load-costume.js
> +            costume.skinId = runtime.renderer.createBitmapSkin(imageElement, costume.bitmapResolution, rotationCenter);
I would expect this to return the `skinId`, which the consumer could use in its own `then` rather than altering the costume object passed in.

2017-03-27 19:28 UTC, paulkaplan commented on src/import/load-costume.js
> +            costume.skinId = runtime.renderer.createBitmapSkin(imageElement, costume.bitmapResolution, rotationCenter);
@rschamp I agree, but this code was just moved from the existing `loadCostume` function in the sb2importer. @cwillisf is there a reason it was done that way?

2017-03-27 20:36 UTC, cwillisf commented on src/import/load-costume.js
> +            costume.skinId = runtime.renderer.createBitmapSkin(imageElement, costume.bitmapResolution, rotationCenter);
The short version: it was easier to do it this way in `sb2import` but there's no need to do it here if you'd like a different interface. If it does stay like this, I almost feel like it should be an instance method on a `Costume` object.

2017-03-28 17:47 UTC, paulkaplan commented
@rschamp do you know why this is failing on the CI?

2017-03-28 17:51 UTC, rschamp requested changes

2017-03-28 17:51 UTC, rschamp commented on src/import/load-costume.js
> +            costume.skinId = runtime.renderer.createBitmapSkin(imageElement, costume.bitmapResolution, rotationCenter);
@paulkaplan I think we should have it return the id here, then over at https://github.com/LLK/scratch-gui/pull/282/files#diff-f0dbeaecf9325f943b76a2cc14612110R21 we don't need that null `skinId`

2017-03-28 19:37 UTC, paulkaplan commented on src/import/load-costume.js
> +            costume.skinId = runtime.renderer.createBitmapSkin(imageElement, costume.bitmapResolution, rotationCenter);
is there a function i can call when that promise resolves with the skinId to apply the skinId to the costume?

2017-03-28 19:37 UTC, paulkaplan commented on src/import/load-costume.js
> +            costume.skinId = runtime.renderer.createBitmapSkin(imageElement, costume.bitmapResolution, rotationCenter);
@rschamp @cwillisf is there a function i can call when that promise resolves with the skinId to apply the skinId to the costume?

2017-03-31 15:33 UTC, rschamp approved these changes

2017-03-31 16:52 UTC, merged