Added testing to rendered-target
LLK/scratch-vm pull request #527
Opened 2017-04-07 18:54 UTC by SillyInventor

Added a fake renderer with known predictable output
Added testing for most if not all functions

### Resolves

Partially addresses #471

### Proposed Changes

Add unit testing to rendered-target

### Reason for Changes

Everybody likes testing

### Test Coverage

Yup.

2017-04-20 14:39 UTC, thisandagain commented
Sorry for the slow turnaround on this PR @SillyInventor. This looks great!

2017-04-20 14:41 UTC, thisandagain requested changes
This is great. Really minor comments / nitpicks.

2017-04-20 14:41 UTC, thisandagain commented on test/unit/sprites_rendered-target.js
> +var fakeRenderer = function (){
Inconsistent spacing after `()`.

2017-04-20 14:41 UTC, thisandagain commented on test/unit/sprites_rendered-target.js
> +
Extra line break

2017-04-20 14:41 UTC, thisandagain commented on test/unit/sprites_rendered-target.js
> +var fakeRenderer = function (){
I feel like the "fakeRenderer" might be better split out and added as a module to "test/fixtures". Thoughts?

2017-04-24 14:11 UTC, SillyInventor commented
It is I who should apologize for the timing of the commit. I've been very busy testing tutorial layouts with students etc. and just sitting on this rather than committing. Hopefully the edits are good.

2017-04-24 14:15 UTC, thisandagain commented
Looks great @SillyInventor. Thanks for splitting that out. Just for documentation:

## Before
![image](https://cloud.githubusercontent.com/assets/747641/25341456/d7cd1210-28d6-11e7-99ec-9571972d50b5.png)

## After
![image](https://cloud.githubusercontent.com/assets/747641/25341468/e15e817e-28d6-11e7-9f7e-b0d6fab4aa6c.png)

2017-04-24 14:15 UTC, thisandagain approved these changes

2017-04-24 14:15 UTC, merged