Use ES6, convert to ES6-style classes
LLK/scratch-vm pull request #534
Opened 2017-04-17 23:58 UTC by rschamp

### Resolves

_What Github issue does this resolve (please include link)?_
#3 

### Proposed Changes

_Describe what this Pull Request does_
Updates the build system to use Babel, and updates class syntax to ES6 classes.

### Reason for Changes

_Explain why these changes should be made_
In our discussion last week we decided to settle on ES6 everywhere, including here.

### Test Coverage

_Please show how you have added tests to cover your changes_
It works!

2017-04-19 19:58 UTC, cwillisf requested changes
Thanks for doing this, @rschamp!
Overall it looks great... just a couple nits.

2017-04-19 19:58 UTC, cwillisf commented on src/blocks/scratch3_pen.js
> +    static get DEFAULT_PEN_STATE () {
😎

2017-04-19 19:58 UTC, cwillisf commented on src/blocks/scratch3_procedures.js
> +                if (args.hasOwnProperty(`input${i}`)) {
This is one of my favorite ES6 features: more readable AND (possibly) more efficient!

2017-04-19 19:58 UTC, cwillisf commented on src/engine/blocks.js
> +            }>`;
The formatting got weird here RE: newlines. Looks like there's a `+` that could be eliminated, too.
I noticed a similar newline issue further down in this file, too.

2017-04-19 19:58 UTC, cwillisf commented on src/import/load-costume.js
> +        promise = promise.then(costumeAsset => new Promise((resolve, reject) => {
IMO this actually became less readable... do you think a newline would help?

2017-04-19 21:57 UTC, rschamp commented
@cwillisf Agreed on your points. Also needed to merge, so merged and ES6-ified the merged code.

2017-04-19 21:58 UTC, rschamp commented
Also just realized since we're now on Node 6, we can use ES6 syntax at the root of the project too... should I do that? I think it pretty much can be done with `eslint --fix`.

2017-04-19 22:11 UTC, cwillisf approved these changes

2017-04-19 22:13 UTC, cwillisf commented
I do think we should move tests to ES6 but maybe that should be a separate PR? I don't feel strongly about that :)

2017-04-20 14:33 UTC, thisandagain reviewed
This looks good to me. I'm curious if the conversion via Babel is affecting performance. Have you run any bench tests?

2017-04-20 14:33 UTC, thisandagain commented
Re: tests. I think it's probably good to hold off on migrating the test suite to ES6. It would good to file an issue for it though.

2017-04-20 19:48 UTC, rschamp commented
@thisandagain Nothing super thorough, but comparing the profiles of the default project running in the current VM playground and the ES6 version, nothing stands out as being Babel-related to me.

2017-04-20 21:06 UTC, merged