Device manager client
LLK/scratch-vm pull request #549
Opened 2017-04-28 21:55 UTC by cwillisf

### Resolves

Progress toward #518 

### Proposed Changes

This change adds a new type of I/O device, called `DeviceManager`, which acts as a client for the Scratch Device Manager application. An instance of this new type is now available in the runtime's list of I/O devices and is called `deviceManager`.

### Test Coverage

A few basic tests for the new `DeviceManager` I/O device have been added as part of this change.

2017-05-03 23:30 UTC, cwillisf commented on src/io/deviceManager.js
> +        this._connectionTimeout = setTimeout(() => this.onTimeout(), DeviceOpener.CONNECTION_TIMEOUT_MS);
The `() => this.foo()` here is being used as a substitute for `foo.bind(this)`

2017-05-05 01:09 UTC, rschamp requested changes

2017-05-05 01:09 UTC, rschamp commented on package.json
> +    "socket.io-client": "^1.7.3",
Both of these should probably be explicitly pinned since they're used within the application.

2017-05-05 01:09 UTC, rschamp commented on src/io/deviceManager.js
> +        this._connectionTimeout = setTimeout(() => this.onTimeout(), DeviceOpener.CONNECTION_TIMEOUT_MS);
Fine with me this way.  Using `bind` at run time rather than construct time is slightly less efficient, but not for something like this that won't be called frequently. I think the other thing you could do is use `bindAll` in the constructor for instance methods like we do in the GUI (where it's important to not `bind` in `render`). Then `this.onTimeout` should already be bound.

2017-05-05 01:09 UTC, rschamp commented on src/io/deviceManager.js
> +        this.removeSocket();
I don't see this defined anywhere, maybe left behind from a refactor?

2017-05-09 14:54 UTC, rschamp requested changes
@cwillisf I'm having trouble building this for some reason. I get warnings, which you can also see in the log for the Travis build:
```
    WARNING in ./~/ws/lib/Validation.js
    Module not found: Error: Can't resolve 'utf-8-validate' in '/Users/rschamp/Documents/Scratch/scratch-vm/node_modules/ws/lib'
     @ ./~/ws/lib/Validation.js 10:19-44
     @ ./~/ws/lib/Receiver.js
     @ ./~/ws/index.js
     @ ./~/engine.io-client/lib/transports/websocket.js
     @ ./~/engine.io-client/lib/transports/index.js
     @ ./~/engine.io-client/lib/socket.js
     @ ./~/engine.io-client/lib/index.js
     @ ./~/engine.io-client/index.js
     @ ./~/socket.io-client/lib/manager.js
     @ ./~/socket.io-client/lib/index.js
     @ ./src/io/deviceManager.js
     @ ./src/engine/runtime.js
     @ ./src/virtual-machine.js
     @ ./src/index.js

    WARNING in ./~/ws/lib/BufferUtil.js
    Module not found: Error: Can't resolve 'bufferutil' in '/Users/rschamp/Documents/Scratch/scratch-vm/node_modules/ws/lib'
     @ ./~/ws/lib/BufferUtil.js 10:19-40
     @ ./~/ws/lib/Sender.js
     @ ./~/ws/index.js
     @ ./~/engine.io-client/lib/transports/websocket.js
     @ ./~/engine.io-client/lib/transports/index.js
     @ ./~/engine.io-client/lib/socket.js
     @ ./~/engine.io-client/lib/index.js
     @ ./~/engine.io-client/index.js
     @ ./~/socket.io-client/lib/manager.js
     @ ./~/socket.io-client/lib/index.js
     @ ./src/io/deviceManager.js
     @ ./src/engine/runtime.js
     @ ./src/virtual-machine.js
     @ ./src/index.js
```

And then while that's happening, the GUI won't build with the vm linked:

```
ERROR in ../scratch-vm/dist/node/scratch-vm.js
Module not found: Error: Can't resolve 'fs' in '/Users/rschamp/Documents/Scratch/scratch-vm/dist/node'
 @ ../scratch-vm/dist/node/scratch-vm.js 1038:17-30
 @ ./src/containers/gui.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8601 ./src/index.jsx

ERROR in ../scratch-vm/dist/node/scratch-vm.js
Module not found: Error: Can't resolve 'net' in '/Users/rschamp/Documents/Scratch/scratch-vm/dist/node'
 @ ../scratch-vm/dist/node/scratch-vm.js 7283:17-31
 @ ./src/containers/gui.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8601 ./src/index.jsx

ERROR in ../scratch-vm/dist/node/scratch-vm.js
Module not found: Error: Can't resolve 'child_process' in '/Users/rschamp/Documents/Scratch/scratch-vm/dist/node'
 @ ../scratch-vm/dist/node/scratch-vm.js 34353:17-41
 @ ./src/containers/gui.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8601 ./src/index.jsx

ERROR in ../scratch-vm/dist/node/scratch-vm.js
Module not found: Error: Can't resolve 'tls' in '/Users/rschamp/Documents/Scratch/scratch-vm/dist/node'
 @ ../scratch-vm/dist/node/scratch-vm.js 34365:17-31
 @ ./src/containers/gui.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8601 ./src/index.jsx
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 541 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
        [1] ./~/html-webpack-plugin/lib/loader.js!./src/index.ejs 627 bytes {0} [built]
        [2] (webpack)/buildin/global.js 509 bytes {0} [built]
        [3] (webpack)/buildin/module.js 517 bytes {0} [built]
webpack: Failed to compile.
```

Any ideas?  I found this, looking for the bufferutils warning: https://github.com/socketio/socket.io-client/issues/933

2017-05-09 16:25 UTC, cwillisf commented
The warnings are related to this, I believe: https://github.com/socketio/socket.io-client/issues/933

However, I hadn't seen those GUI errors. I'll investigate.

2017-05-11 19:19 UTC, cwillisf commented
Using `require('socket.io-client/dist/socket.io')` fixes the build warnings in `scratch-vm` as well as the errors in `scratch-gui`.

@rschamp: you mentioned in a separate discussion that this change has increased the size of the `scratch-vm` build output quite a bit. That's true in the absolute sense (622 KB -> 973 KB) it's dwarfed by the rest of `scratch-gui`: `scratch-gui`'s `gui.js` build output increases by very roughly the same raw amount but a much lower percentage (7.2 MB -> 7.4 MB). I still think it's worth trying to decrease the build size but maybe not as a right-this-moment priority.

2017-05-23 20:31 UTC, rschamp approved these changes

2017-05-24 21:43 UTC, merged