Feature/serialization
LLK/scratch-vm pull request #552
Opened 2017-05-04 17:07 UTC by rschamp

### Resolves
Requires https://github.com/LLK/scratch-storage/pull/11
Resolves https://github.com/LLK/scratch-vm/issues/550 and https://github.com/LLK/scratch-gui/issues/329
Also is a start on https://github.com/LLK/scratch-vm/issues/194 (not final until we have a parser).

### Proposed Changes

This is a merge of the work done by @morantsur and @thisandagain into the current VM.
- Add JSON serialization of project data, to serve as a first iteration of SB3 JSON
- Add sb3 json de/serializer
- Refactor sb2 loading to use a sb2 deserializer
- Stop storing costume and sound data in the VM state. 

### Reason for Changes

- Gives us a way to save/load sb3 files.
- Improve GUI performance by not sending costume and sound data in target updates. The GUI wants to compare the targets, and walking ArrayBuffers is not very fun

/cc @thisandagain @paulkaplan

2017-05-05 18:51 UTC, cwillisf requested changes

2017-05-05 18:51 UTC, cwillisf commented on src/virtual-machine.js
> +        if (typeof json !== 'object') return;
These early-outs should probably log an error or something (same in `addSprite2`)

2017-05-05 18:51 UTC, cwillisf commented on src/virtual-machine.js
> +            this.editingTarget = this.runtime.targets[1];
There's no requirement for a project to include a sprite. I'd recommend something equivalent to:
`this.editingTarget = this.runtime.targets[targets.length > 1 ? 1 : 0];`

That way the stage is selected if there are no sprites. If there isn't even a stage then the editing target will be `undefined`, which I guess is the best we can hope for in that situation...

2017-05-08 18:15 UTC, cwillisf commented
BTW: what happened with the history on this branch?

2017-05-08 21:29 UTC, rschamp commented
That's the actual history :)  I will squash when I merge.

2017-05-11 13:59 UTC, rschamp commented
@cwillisf Updated

2017-05-11 16:12 UTC, cwillisf approved these changes

2017-05-11 17:07 UTC, merged