Run blocks with boxes checked next to them
LLK/scratch-vm pull request #558
Opened 2017-05-08 20:56 UTC by fsih

When a checkbox is checked in the flyout, calculate the value of that block every frame in the VM. Does not yet deal with single sprite scoped variables.

2017-05-08 20:57 UTC, fsih commented
Does this need tests?

2017-05-09 15:27 UTC, rschamp commented on src/virtual-machine.js
> +        if (['create', 'change'].indexOf(e.type) !== -1) {
We should explain this whitelist in the docstring

2017-05-09 15:27 UTC, rschamp approved these changes

2017-05-09 15:29 UTC, rschamp commented
It would be great to have tests for this. But since this is still incomplete, we can write them as we finish the feature... we might be making more work for ourselves writing them before we finish figuring out exactly how it should work.

2017-05-09 16:15 UTC, mrjacobbloom commented
something to watch out for: right now no reporters should have any side effects, but if custom reporters are implemented that might become an issue

2017-05-10 13:23 UTC, rschamp commented
@mrjacobbloom That's a good point! For that reason we will probably not allow monitoring of custom reporters if they are added. (And probably the reason you can't monitor custom reporters in Snap!)

2017-05-10 14:26 UTC, CosmicWebServices requested changes
Travis does not pass

2017-05-10 14:26 UTC, CosmicWebServices commented on src/engine/execute.js
> +                        label: blockContainer.getOpcode(blockContainer.getBlock(currentBlockId)), // @todo(dd) how to handle translation here?
100:1   error    Line 100 exceeds the maximum line length of 120       max-len

Travis error

2017-05-10 15:22 UTC, fsih commented on src/virtual-machine.js
> +        if (['create', 'change'].indexOf(e.type) !== -1) {
Done

2017-05-10 15:25 UTC, fsih commented
This code won't do anything until the blockly change to fire checkbox events is in. https://github.com/paulkaplan/scratch-blocks/tree/emit-checkbox-event

2017-05-10 15:27 UTC, merged