Select the last target instead of the first after deleting
LLK/scratch-vm pull request #594
Opened 2017-06-07 13:08 UTC by paulkaplan

### Resolves

_What Github issue does this resolve (please include link)?_
Fixes https://github.com/LLK/scratch-gui/issues/294
### Proposed Changes

_Describe what this Pull Request does_
Prefer selecting the last target instead of the first (the stage). This way it will always try to stay selected on a target. 

### Reason for Changes

_Explain why these changes should be made_
https://github.com/LLK/scratch-gui/issues/294

--- 

@rschamp sorry I know this was assigned to you, but I figured it was just a one liner. Is this what you had in mind?

2017-06-08 14:54 UTC, fsih approved these changes

2017-06-08 15:09 UTC, rschamp requested changes
I would hope to match Scratch 2.0 behavior, which I think will end up being a bit more than a one-liner.  That behavior is to select the sprite before the deleted sprite, or the first sprite if you deleted the first sprite.

Happy to work on this unless you want to revise what you have to behave that way.

2017-06-12 12:40 UTC, paulkaplan commented
@rschamp addressed the comments in 9c5d43e

2017-06-12 12:41 UTC, merged

2017-06-12 13:51 UTC, rschamp commented on src/virtual-machine.js
> +        const targetIndexBeforeDelete = this.runtime.targets.map(t => t.id).indexOf(target.id);
Is this different from `this.runtime.targets.indexOf(target)`?