Implement message dispatch system
LLK/scratch-vm pull request #640
Opened 2017-07-13 18:41 UTC by cwillisf

### Proposed Changes

This message dispatch system allows a "service" to register itself under a particular name, and then anyone can call any method on that service from any context (the main "window" thread or any worker). Return values are passed back through promise resolution.

### Reason for Changes

This will make it much easier to put extensions inside workers: we can expose any services needed by extensions through this message dispatch system, but otherwise extensions will be unable to interact with the editor. If we find that it's necessary, we could even add some form of permissions to the message dispatch system with relatively little work.

### Test Coverage

I was experimenting with https://www.npmjs.com/package/tiny-worker as a way to mock / polyfill web workers for the purpose of testing in Node.js, but I was unable to get it working in a reasonable amount of time. I definitely think we should revisit this and add tests at some point.

2017-07-14 15:54 UTC, rschamp commented on src/dispatch/central-dispatch.js
> +self.Scratch.dispatch = dispatch;
Is this left in for debugging? Seems like it should be something the app does.

2017-07-21 20:25 UTC, cwillisf commented
Rebased on `develop` @ e249c5c2525316a369a2f6a5220467eb6c1d60b5 to fix `package.json` conflicts

2017-08-01 20:29 UTC, rschamp requested changes
@cwillisf Looks great overall! Just a few notes from our walkthrough.

2017-08-01 20:29 UTC, rschamp commented on src/dispatch/central-dispatch.js
> +        return new Promise(resolve => {
We should add an explanatory comment about why this returns a Promise (for consistency).

2017-08-01 20:29 UTC, rschamp commented on src/dispatch/central-dispatch.js
> +        const [service, method, callbackId, ...args] = /** @type {[string, string, *]} */ event.data;
Maybe `event.data` should come as an object with a `type` key. Either way we should `try...except` here in case the message isn't well formed.

2017-08-01 20:29 UTC, rschamp commented on src/dispatch/central-dispatch.js
> +    _callback (callbackId, result, error) {
`result, error` looks reversed to me.

2017-08-14 13:49 UTC, rschamp approved these changes
Looks good @cwillisf! Can't wait to see this in action.

2017-08-14 13:50 UTC, rschamp commented
@paulkaplan @fsih @ericrosenbaum should also take a look at this, at least just to be familiar with what's going in for the extensions work.

2017-08-17 17:57 UTC, merged