Renaming sprite/costume/sound/backdrop updates corresponding blocks.
LLK/scratch-vm pull request #931
Opened 2018-02-05 22:27 UTC by kchadha

### Resolves

Resolves #912

### Proposed Changes

Updates blocks after a sprite, sound, costume, or backdrop has been renamed.

### Reason for Changes

#912

### Test Coverage

Fixed existing renameSprite tests so that the new update function can get called correctly.

2018-02-09 14:57 UTC, paulkaplan requested changes
I think we should try to include some unit tests in `engine_blocks` for the new public `updateAssetName` function. That file has pretty good coverage, wouldn't want to let it slip.

2018-02-09 14:57 UTC, paulkaplan commented
@kchadha functionality/code wise this all looks good, but I think we need some unit tests on `engine_blocks`

2018-02-09 22:35 UTC, kchadha commented
@paulkaplan, added unit tests!

2018-02-12 14:10 UTC, paulkaplan approved these changes
LG!

2018-02-12 16:53 UTC, merged