Implement for-each block
LLK/scratch-vm pull request #963
Opened 2018-03-05 20:45 UTC by towerofnix

### Resolves

Resolves #959. Should not be merged before LLK/scratch-blocks#1394.

### Proposed Changes

Adds the implementation for the "for each" block. A code comment that explains how it works is included in the implementation, and is quoted below:

The for-each block has two different but similar modes of operation,
based on the value to be iterated:

>The for-each block has two different but similar modes of operation,
>based on the value to be iterated:
>
> 1. If the value is a string, keep INTERNAL track of the index. The value assigned to the Scratch variable will be the letter at the current index, which will increase by 1 each tick. For example:
>
>    ```
>    for each (x) in [abcdef]:
>      say (x)
>    ```
>
>    ..is equivalent to:
>
>    ```
>    set (i_) to 0
>    repeat until (i_) > length of [abcdef]:
>      change (i_) by 1
>      set (x) to letter (i_) of [abcdef]
>      say (x)
>    ```
>
>    In this example, i_ is effectively invisible to the Scratch code: there is no way to view or change it. Also, changing (x) has no effect on the next iteration.
>
> 2. If the value is a number, DO NOT keep internal track of the index. When for-each is passed a number, it iterates over all the numbers from 1 to that number (inclusive). For example:
>
>    ```
>    for each (x) in [10]:
>      say (x)
>    ```
>
>    ..is equivalent to:
>
>    ```
>    set (x) to 0
>    repeat until (x) > 10:
>      change (x) by 1
>      say (x)
>    ```
>
>    The critical difference is that (x) is just a normal Scratch variable. Changing it DOES have an effect on the next iteration. This makes it possible to "skip" items, or to go back, et cetera. For example:
>
>    ```
>    for each (x) in [10]:
>      if (x) mod 4 = 0:
>        say [Mod 4 - Skip the next.]
>        change (x) by 1
>      else:
>        say x
>    ```
>
>    ..would say 1, 2, 3, "Mod 4", 6, 7, "Mod 4", 10.
>
>The mode of operation above is decided at the beginning of the for-each loop, and changing the value that is being iterated *while* it is being iterated does not change the mode. 

### Reason for Changes

For compatibility with Scratch 2.0 projects that use the hacked "for each" block. Also, as a powerful and convenient block. What it can do is described above, but here are some examples:

Basic fizz-buzz - no special usage of "for" loop, it simply iterates a range of numbers:

![Fizz-buzz script](https://user-images.githubusercontent.com/9948030/36998316-dbf61c24-2092-11e8-9827-3ee3da9e51e5.png)

This says "1, 2, fizz, 4, buzz, fizz, 7, 8, fizz, buzz, 11, fizz, 13, 14, fizz buzz".

Changing the iterator variable while running - this skips numbers that are immediately after numbers divisible by 4:

![Skip past (divisible by 4)+1](https://user-images.githubusercontent.com/9948030/36998388-222edbe0-2093-11e8-898d-53e824629bb4.png)

This says "1, 2, 3, mod 4, 6, 7, mod 4, 10".

Manipulating a list while it is being iterated - this is a bit more complicated! When the loop reaches items equal to "baddy", those items are removed, and the loop continues from the item that appears in baddy's place. When the loop reaches items equal to "boom", the "boom" is removed, and four items ("wow!!!", "watch out for the sneaky", "baddy", and "cool!!!") are added in its place. The loop then continues from just *past* those items.

![baddyboom](https://user-images.githubusercontent.com/9948030/36998479-74343e80-2093-11e8-8247-3eb59df83bbd.png)

This prints:

* 1: a
* 2: b
* 3: baddy
* 3: boom
* 7: baddy
* 7: c

And the resulting modified list looks like "a, b, wow!!!, watch out for the sneaky, baddy, cool!!!, c".

All of the above changes maintain compatibility with 2.0 projects, assuming those 2.0 projects did not modify the iterator variable, since that would not have an effect in 2.0 (since the index was entirely stored and counted internally, then copied into the iterator variable). Since the "for each" block was used so rarely in 2.0, I think it's not unreasonable to break those for the sake of making the block slightly more versatile.

### Test Coverage / To Do

**This has been tested manually and has unit tests, but has not been tested on existing Scratch 2.0 projects.** I still need to do that before this should be merged.

**Also, there is not yet code to handle `doForLoop` in Scratch 2.0 projects.** This must also be implemented and tested.

2018-03-05 20:55 UTC, towerofnix commented
Note - Travis CI failed here:

```
./test/integration/hat-threads-run-every-frame.js ... 53/54
  edge activated hat thread runs once every frame
  not ok expect truthy value
    at:
      line: 50
      column: 15
      file: test/integration/hat-threads-run-every-frame.js
      function: vm.loadProject.then
    stack: |
      vm.loadProject.then (test/integration/hat-threads-run-every-frame.js:50:15)
    source: |
      t.assert(vm.runtime.threads[0].status === Thread.STATUS_DONE);
```

This test succeeded in a different attempt on Travis, and the error didn't happen locally, so I doubt this is related to this PR.

2018-03-05 21:47 UTC, towerofnix commented
Okay, SB2 importing and manual testing complete. All projects (besides one that fails to import for unrelated reasons) load and run well. It looks like that test case isn't failing anymore now, as well.

2018-03-22 20:16 UTC, kchadha commented
@towerofnix This is awesome work! Thank you for the thorough documentation, it was very helpful in understanding the behavior of the block and the two modes that have been implemented.

Looking through the proposed changes, I am noticing some deviations from the Scratch 2.0 behavior (they are documented below).

Since this block is being added to Scratch 3.0 specifically for maintaining compatibility with older projects, I think the behavior of the 3.0 block should have a one-to-one correspondence with the Scratch 2.0 block. Thus, I don't think we should change any behavior from the 2.0 block or add any features that the 2.0 block does not have.

Deviations I noticed: 
In Scratch 2.0, it is not possible to ‘skip’ items like you mention in the documentation for the forEach function. This makes the following program behave differently in Scratch 2.0 vs. Scratch 3.0:

![image](https://user-images.githubusercontent.com/1786240/37746192-688e4116-2d4f-11e8-913a-63f21ddda39a.png)

Another difference I saw was in the behavior of this project:

![image](https://user-images.githubusercontent.com/1786240/37746247-ac8c9386-2d4f-11e8-9bb9-db4205a2321b.png)

In Scratch 2.0, running this project results in the scratch cat saying 1, then 2, then 3, 3 times. In Scratch 3.0, running this project results in the scratch cat cycling from 1-3 only once.

Finally, as far as I can tell, I don't think the scratch 2.0 for each block supports iterating over letters of strings like you've described in your documentation.

In order to get this merged into develop, the 3.0 behavior should be as close to the 3.0 behavior as possible.

2018-03-22 20:17 UTC, kchadha requested changes
Changes requested in comment.

2018-03-22 21:42 UTC, towerofnix commented
Alright, I'll change those - admittedly those changes would far better fit an extension :)

2018-03-28 14:06 UTC, kchadha commented
@towerofnix I think these changes are no longer working against develop, can you investigate what's going on? It also seems that unit tests are failing.

2018-03-28 14:39 UTC, towerofnix commented
@kchadha Whoops, I forgot to remove the tests for the extra behavior. Thanks for pinging me on this; tests should be working now.

2018-03-28 14:50 UTC, kchadha approved these changes

2018-03-28 14:51 UTC, kchadha commented
@towerofnix, thanks for fixing the tests! Everything looks good.

2018-03-28 14:52 UTC, merged